# Generated by Django 3.2.8 on 2021-10-24 03:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('description', models.TextField(max_length=500, verbose_name='Description')),
                ('type', models.CharField(choices=[('BUG', 'Bug'), ('UI', 'User-Interface'), ('FEATURE', 'Feature')], default='FEATURE', max_length=11, verbose_name='Type')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('IN PROGRESS', 'In progress'), ('RESOLVED', 'Resolved')], default='OPEN', max_length=11, verbose_name='Status')),
                ('priority', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('NORMAL', 'Normal'), ('LOW', 'Low')], default='NORMAL', max_length=8, verbose_name='Priority')),
                ('votes', models.IntegerField(default=0, verbose_name='Votes')),
                ('assignees', models.ManyToManyField(related_name='assignees', to=settings.AUTH_USER_MODEL, verbose_name='Assignees')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_creator', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('description', models.TextField(max_length=500, verbose_name='Description')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracker_creator', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('updater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracker_updater', to=settings.AUTH_USER_MODEL, verbose_name='Updater')),
            ],
            options={
                'verbose_name': 'Tracker',
                'verbose_name_plural': 'Trackers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TicketComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('description', models.TextField(max_length=500, verbose_name='Description')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticketcomment_creator', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.ticket', verbose_name='Ticket')),
                ('updater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticketcomment_updater', to=settings.AUTH_USER_MODEL, verbose_name='Updater')),
            ],
            options={
                'verbose_name': 'Ticket comment',
                'verbose_name_plural': 'Ticket comments',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='tracker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.tracker', verbose_name='Tracker'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='updater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_updater', to=settings.AUTH_USER_MODEL, verbose_name='Updater'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='vote_profiles',
            field=models.ManyToManyField(related_name='vote_profiles', to=settings.AUTH_USER_MODEL, verbose_name='Vote profiles'),
        ),
    ]
