# Generated by Django 3.2.8 on 2021-10-24 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['title'], 'verbose_name': 'Ticket', 'verbose_name_plural': 'Tickets'},
        ),
        migrations.AlterModelOptions(
            name='ticketcomment',
            options={'ordering': ['title'], 'verbose_name': 'Ticket comment', 'verbose_name_plural': 'Ticket comments'},
        ),
        migrations.AlterModelOptions(
            name='tracker',
            options={'ordering': ['title'], 'verbose_name': 'Tracker', 'verbose_name_plural': 'Trackers'},
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='name',
        ),
        migrations.RemoveField(
            model_name='ticketcomment',
            name='description',
        ),
        migrations.RemoveField(
            model_name='ticketcomment',
            name='name',
        ),
        migrations.RemoveField(
            model_name='tracker',
            name='name',
        ),
        migrations.AddField(
            model_name='ticket',
            name='title',
            field=models.CharField(default='', max_length=20, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='ticketcomment',
            name='comment',
            field=models.TextField(default='', max_length=500, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='ticketcomment',
            name='title',
            field=models.CharField(default='', max_length=20, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='tracker',
            name='title',
            field=models.CharField(default='', max_length=20, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(default='', max_length=500, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='type',
            field=models.CharField(choices=[('BUG', 'Bug'), ('UI', 'User-Interface'), ('FEATURE', 'Feature')], default='BUG', max_length=11, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='description',
            field=models.TextField(default='', max_length=500, verbose_name='Description'),
        ),
    ]
