# Generated by Django 3.2.8 on 2021-10-29 05:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0003_auto_20211026_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='vote_profiles',
            field=models.ManyToManyField(blank=True, related_name='vote_profiles', to=settings.AUTH_USER_MODEL, verbose_name='Vote profiles'),
        ),
    ]
