# Generated by Django 3.2.8 on 2021-10-29 05:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0004_alter_ticket_vote_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='assignees',
            field=models.ManyToManyField(blank=True, related_name='assignees', to=settings.AUTH_USER_MODEL, verbose_name='Assignees'),
        ),
    ]
